### ISSUE TITLE
Godot Not seeing Plugin

### ISSUE THREAD

**Issue by kenneth-leblanc** [peterhoglund/Calendar-Library#3]
I have tried in both Godot 4.2 and 4.3. In both cases I followed the instructions in the Godot Documentation for installing plugins.
https://docs.godotengine.org/en/stable/tutorials/plugins/editor/installing_plugins.html

With an addons folder created and the calendar_library folder and it's contents added I see nothing in the plugins section of Project > Project Settings.
I don't see a plugin.cfg in the folder structure anywhere.

**Comment by peterhoglund** [comment]
This is because this is a script library addon and not a plugin. You don't have to activate it to use it. Create a new calendar object with `var calendar: Calendar = Calendar.new()` and use the class methods to build your calendar. You'll find documentation for all the methods in the editor's documentation. Search for Calendar and you should see it.
